apiVersion: v1
kind: ConfigMap
metadata:
  name: progressive-delivery-config
  namespace: progressive
data:
  UNLEASH_URL: "http://34.63.204.7:4242/"
  UNLEASH_APP_NAME: "progressive-delivery"
  UNLEASH_ENVIRONMENT: "development"
  DB_HOST: "mysql"
  DB_PORT: "3306"
  DB_NAME: "progressive_delivery"
  DB_USER: "app"
---
apiVersion: v1
kind: Secret
metadata:
  name: progressive-delivery-secrets
  namespace: progressive # Added namespace
type: Opaque
stringData:
  UNLEASH_API_TOKEN: "default:development.48c0697b5a989ad45722b32ffdb11d58288b590f9a05b06e5e6ed702"
  DB_PASSWORD: "apppass"
  SECRET_KEY: "dev-secret"

